config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :mytasks, only: [:index]
  resource :profile, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def author_name
    user.display_name
  end

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :tasks, dependent: :destroy

  def task_authors
    task_authors = Set.new
    author_ids = Set.new

    self.tasks.each do |task|
      unless author_ids.include?(task.user.id)
        task_authors.add(task.user)
        author_ids.add(task.user.id)
      end
    end

    task_authors
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :task
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  nickname   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text
#  deadline   :date
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy

  def author_name
    user.display_name
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_one :profile, dependent: :destroy

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def has_written_board?(board)
    boards.exists?(id: board.id)
  end

  def has_written_task?(task)
    tasks.exists?(id: task.id)
  end

  def my_profile?(profile)
    profile.exists?(user_id: current_user)
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: 'ボードを作成しました'
    else
      flash.now[:error] = 'ボードの作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: 'ボードを更新しました'
    else
      flash.now[:error] = 'ボードの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def new
    task = Task.find(params[:task_id])
    @comment = task.comments.build
  end

  def create
    task = Task.find(params[:task_id])
    @comment = task.comments.build(comment_params)
    if @comment.save
      redirect_to board_task_path(task.board, task), notice: 'ボードを作成しました'
    else
      flash.now[:error] = 'ボードの作成に失敗しました'
      render :new
    end
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    comment.destroy!
    redirect_to board_task_path(comment.task), notice: '削除に成功しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

end

app/controllers/mytasks_controller.rb
class MytasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @mytasks = current_user.tasks
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
  end

  def update
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = 'プロフィールを更新できませんでした'
      render :edit
    end
  end

  private
  def set_profile
    @profile = current_user.prepare_profile
  end

  def profile_params
    params.require(:profile).permit(:nickname, :avatar)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks
  end

  def show
    @task = Task.find(params[:id])
    @comments = @task.comments
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    if @task.save
      redirect_to board_task_path(id: @task.id), notice: 'ボードを作成しました'
    else
      flash.now[:error] = 'ボードの作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to board_task_path(@task), notice: 'ボードを更新しました'
    else
      flash.now[:error] = 'ボードの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(task.board), notice: '削除に成功しました'
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :deadline, :user_id)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  %h2 Edit Board
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true) do |f|
    %div
      = f.label :title, 'Agenda'
    %div
      = f.text_field :title, class: 'text'
    %br/
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/index.html.haml
.container
  - @boards.each do |board|
    = link_to board_path(board) do
      .card
        .card_content
          .card_content_title
            = board.title
          .card_content_detail
            = board.content
          .card_content_task
            .card_content_task_author
              - board.task_authors.each do |task_author|
                = image_tag task_author.avatar_image
            .card_content_task_count
              %span= board.tasks.count
              = image_tag "message-square-outline.png"
  = link_to new_board_path do
    .new-board
      %span + Add new board

app/views/boards/new.html.haml
.container
  %h2 New Board
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true) do |f|
    %div
      = f.label :title, 'Agenda'
    %div
      = f.text_field :title, class: 'text'
    %br/
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/show.html.haml
.container
  .back-link
    .board_title
      %h1= link_to @board.title, root_path
    - if user_signed_in? && current_user.has_written_board?(@board)
      .board_actions
        .dropdown
          = image_tag 'Combined Shape.png', class: 'dropbtn'
          .dropdown-content.mini
            = link_to 'Edit', edit_board_path(@board)
            = link_to 'Delete', board_path(@board), data: { method: 'delete', confirm: '本当に削除してもいいですか？' }
  .board
    .board_content
      = @board.content
    .board_info
      = image_tag @board.user.avatar_image
      %div
        %p= @board.author_name
        %p= @board.display_created_at


  .board
    %h2 Tasks
    - @tasks.each do |task|
      =link_to board_task_path(task.board, task) do
        .board_info
          = image_tag task.user.avatar_image
          %div
            %p= task.author_name
            %p= task.title
    =link_to new_board_task_path(@board) do
      .new-board
        %span + Add new task

app/views/comments/new.html.haml
.container
  %h2 New Comment
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @comment, url: board_task_comments_path, local: true) do |f|
    %div
      = f.label :content, 'Comment'
    %div
      = f.text_area :content, class: 'text'
    = f.hidden_field :user_id, value: current_user.id
    = f.submit 'Submit', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoAppHiro
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/

  %body
    %header.header
      .header_logos
        %p.header_pageTitle
          = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown
          .dropdown_author
            %span= current_user.profile&.nickname
            %div
              = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'Profile', profile_path
            = link_to 'My Task', mytasks_path
            = link_to 'Log out', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'Log in', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/mytasks/index.html.haml
.container
  .board
    %h2 My Tasks
    - @mytasks.each do |mytask|
      =link_to board_task_path(mytask.board, mytask) do
        .board_info
          %div
            %h3= mytask.board.title
            %p= mytask.title
            %p= mytask.deadline

app/views/profiles/edit.html.haml
.container
  %h2 Edit Profile
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'Avatar'
    %div
      = f.file_field :avatar
    %br/
    %div
      = f.label :nickname, 'Nickname'
    %div
      = f.text_field :nickname, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/profiles/show.html.haml
.container
  .profile
    .profile_top
      %h2 Profile
      = link_to 'Edit', edit_profile_path(@profile), class: 'header_loginBtn'
    .profile_image
      - if @profile&.avatar&.attached?
        .profile_image_display
          = image_tag @profile.avatar
      - else
        .profile_image_input
          %span avatar image
    .profile_nickname
      - if @profile&.nickname
        %p= @profile.nickname
      - else
        %p Nickname

app/views/tasks/edit.html.haml
.container
  %h2 Edit Task
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_task_path, local: true) do |f|
    %div
      = f.label :title, 'Task'
    %div
      = f.text_field :title, class: 'text'
    %br/
    %div
      = f.label :content, 'Detail'
    %div
      = f.text_area :content, class: 'text'
    %br/
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/index.html.haml
.container
  - @tasks.each do |task|
    = link_to board_tasks_path(task) do
      .card
        .card_content
          .card_content_title
            = task.title
          .card_content_detail
            = task.content
          .card_content_info
            .card_content_info_image
              = image_tag task.user.avatar_image
              %div
                %p= task.author_name
                %p= task.display_created_at
  = link_to new_task_path do
    .new-task
      %span + Add new task

app/views/tasks/new.html.haml
.container
  %h2 New Task
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_tasks_path, local: true) do |f|
    %div
      = f.label :title, 'Task'
    %div
      = f.text_field :title, class: 'text'
    %br/
    %div
      = f.label :content, 'Detail'
    %div
      = f.text_area :content, class: 'text'
    %br/
    %div
      = f.label :deadline, 'Deadline'
    %div
      = f.date_field :deadline, class: 'text'
    = f.hidden_field :user_id, value: current_user.id
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.container
  %h1.back-link= link_to @task.board.title, board_path(@task.board)
  .task
    .task_title
      %h2= @task.title
    - if user_signed_in? && current_user.has_written_task?(@task)
      .task_actions
        .dropdown
          = image_tag 'Combined Shape.png', class: 'dropbtn'
          .dropdown-content.mini
            = link_to 'Edit', edit_board_task_path(@task.board)
            = link_to 'Delete', board_task_path(@task), data: { method: 'delete', confirm: '本当に削除してもいいですか？' }
    .task_content
      = @task.content
    .task_deadline
      Deadline:
      = @task.deadline
    .task_info
      = image_tag @task.user.avatar_image
      %div
        %p= @task.author_name
        %p hiro
        %p= @task.display_created_at

  .task
    %h2 Comments
    - @comments.each do |comment|
      .task_info
        = image_tag comment.user.avatar_image
        %p= comment.content
    =link_to new_board_task_comment_path(@task.board, @task) do
      .new-board
        %span + Add new comment